function outS = runEcgAutoDiagPy(ecg_chunked)

% Define Python executable file path (Python executables in Conda envs work
% just fine)
pathToPythonExec = '/home/preali/miniconda3/envs/ecg-omop/bin/python';

% Define the directory containing all Python scripts (must end with '/')
pyPath = '/mnt/hdd_data/preali/GitHubProjects/automatic-ecg-diagnosis/';

% Set the Python environment up if it hasn't been done yet.
% pyrun fails when loading Tensorflow, if pyenv is not called from Matlab
% with the ExecutionMode set to OutOfProcess.
pe = pyenv;
if ~strcmp(pe.Executable,pathToPythonExec)
    pe = pyenv('Version',pathToPythonExec,'ExecutionMode','OutOfProcess');
end

% Import modules and functions in the persistent (=across multiple calls to the
% same function) environment generated by pyrun. As it is persistent, we
% need to import functions and supporting modules only if a new
% Python environment has just been created, hence its status is not "Loaded".
needImport = ~strcmp(char(pe.Status),'Loaded');
if needImport
    origPath = cd(pyPath);
    pyrun("from predict_fun import predict_diagnosis, write_hdf5_from_matlab");
end
% Go back to the initial path after the "imports"
if needImport, cd(origPath); end

% Save "ecg_chunked" data to a temporary HDF5 compatible with the automatic ECG
% diagnosis tool
hdf5_out_path = './ecgtemp.hdf5';
pyrun("write_hdf5_from_matlab(hdf5_out_path, hdf5_dataset_name, matlab_array)",...
       hdf5_out_path=hdf5_out_path,hdf5_dataset_name='tracings',matlab_array=ecg_chunked)


% Call the function with the proper arguments from Matlab
% NB: Pandas Dataframes can be converted to Matlab tables starting with
%     Matlab R2024a (https://uk.mathworks.com/help/matlab/matlab_external/python-pandas-dataframes.html).
%     As for 2023a, which is the last version compatible with
%     Python 3.8 (the last version fully compatible with Ribeiro's ECG
%     automated diagnosis tool), we need to unpack the dataframe to its
%     components (namely, "y_score", "diagnosis", and "y_labels").
datapath = hdf5_out_path;
modelpath = [pyPath,'model/model.hdf5'];
[~,y_score,diagnosis,y_labels] = pyrun(...
           "df,y_score,diagnosis,y_labels = predict_diagnosis(path_to_hdf5, path_to_model)",...
           ["df","y_score","diagnosis","y_labels"],...
           path_to_hdf5=datapath,path_to_model=modelpath);

% Convert Python outputs to valid Matlab variables formats
y_score = double(y_score);
y_labels = string(y_labels);
diagnosis = string(diagnosis);

% Prepare the output struct
outS.y_score = y_score;
outS.y_labels = y_labels;
outS.diagnosis = diagnosis;

% Delete (permanently) the temporary HDF5 with the ECG tracings
prevState = recycle('off');
delete(hdf5_out_path);
recycle(prevState);

end