function tableBuilted = tableBuilder(type, rows)
switch type
    % Main table
    case 'notes'
        tableBuilted = table('Size', [rows 10], ...
            'VariableTypes', {'int64','string','string','string','string', 'string','singleNaN','string','string','string'}, ...
            'VariableNames', {'ID','RecordName', 'DatasetName', 'RecordDate', 'RecordEnd', 'Patient', 'Age', 'Sex', 'Diagnosis', 'OtherNotes'});
    
    % Tables without FK
    case 'meas_no_fk'
        tableBuilted = table('Size', [rows 16], ...
            'VariableTypes', {'int64', 'string','string','string','doubleNaN','doubleNaN','doubleNaN','doubleNaN', ...
            'doubleNaN','doubleNaN','doubleNaN','doubleNaN','doubleNaN','doubleNaN','doubleNaN','doubleNaN'}, ...
            'VariableNames', {'ID','RecordName', 'DatasetName', 'Timestamp', 'Lead_I', 'Lead_II', 'Lead_III', ...
            'Lead_aVF', 'Lead_aVR', 'Lead_aVL', 'Lead_V1', 'Lead_V2', 'Lead_V3', 'Lead_V4', 'Lead_V5', 'Lead_V6'});
    case 'rrIntDur_no_fk'
        tableBuilted = table('Size', [rows 6], ...
            'VariableTypes', {'int64', 'string','string','string','doubleNaN','string'}, ...
            'VariableNames', {'ID','RecordName', 'DatasetName', 'StartTimestamp', 'RRIntervalDuration', 'EndTimestamp'});
    case 'annotations_no_fk'
        tableBuilted = table('Size', [rows 11], ...
            'VariableTypes', {'int64', 'string', 'string', 'string', 'doubleNaN', 'string', 'string', 'doubleNaN','doubleNaN', 'doubleNaN', 'string'}, ...
            'VariableNames', {'ID','RecordName', 'DatasetName', 'Timestamp', 'Sample', 'AnnType', 'AnnExplanation', 'SubType', 'Chan', 'Num', 'Comments'});
    case 'hrvMetrics_no_fk'
        tableBuilted = table('Size', [rows 30], ...
            'VariableTypes', {'int64', 'string','string', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', ...
            'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', ...
            'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', ...
            'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', ...
            'doubleNaN', 'doubleNaN'}, ...
            'VariableNames', {'ID','RecordName', 'DatasetName', 'RR', 'NN', 'AVNN', 'SDNN', 'RMSSD', 'pNN50', 'SEM', ...
            'BETA_FFT', 'HF_NORM_FFT', 'HF_PEAK_FFT', 'HF_POWER_FFT', 'LF_NORM_FFT', 'LF_PEAK_FFT', ...
            'LF_POWER_FFT', 'LF_TO_HF_FFT', 'TOTAL_POWER_FFT', 'VLF_NORM_FFT', 'VLF_POWER_FFT',  ...
            'SD1', 'SD2', 'alpha1', 'alpha2', 'SampEn', 'PIP', 'IALS', 'PSS', 'PAS'});

    % Tables with FK
    case 'meas'
        tableBuilted = table('Size', [rows 15], ...
            'VariableTypes', {'int64', 'string','doubleNaN','doubleNaN','doubleNaN','doubleNaN', ...
            'doubleNaN','doubleNaN','doubleNaN','doubleNaN','doubleNaN','doubleNaN','doubleNaN','doubleNaN', 'int64'}, ...
            'VariableNames', {'ID', 'Timestamp', 'Lead_I', 'Lead_II', 'Lead_III', ...
            'Lead_aVF', 'Lead_aVR', 'Lead_aVL', 'Lead_V1', 'Lead_V2', 'Lead_V3', 'Lead_V4', 'Lead_V5', 'Lead_V6', 'FK_ID'});
    case 'rrIntDur'
        tableBuilted = table('Size', [rows 5], ...
            'VariableTypes', {'int64', 'string','doubleNaN','string', 'int64'}, ...
            'VariableNames', {'ID', 'StartTimestamp', 'RRIntervalDuration', 'EndTimestamp', 'FK_ID'});
    case 'annotations'
        tableBuilted = table('Size', [rows 10], ...
            'VariableTypes', {'int64', 'string', 'doubleNaN', 'string', 'string', 'doubleNaN','doubleNaN', ...
            'doubleNaN', 'string', 'int64'}, ...
            'VariableNames', {'ID', 'Timestamp', 'Sample', 'AnnType', 'AnnExplanation', 'SubType', 'Chan', 'Num', 'Comments', ...
            'FK_ID'});
    case 'hrvMetrics'
        tableBuilted = table('Size', [rows 29], ...
            'VariableTypes', {'int64', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', ...
            'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', ...
            'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', ...
            'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', 'doubleNaN', ...
            'doubleNaN', 'doubleNaN', 'int64'}, ...
            'VariableNames', {'ID', 'RR', 'NN', 'AVNN', 'SDNN', 'RMSSD', 'pNN50', 'SEM', ...
            'BETA_FFT', 'HF_NORM_FFT', 'HF_PEAK_FFT', 'HF_POWER_FFT', 'LF_NORM_FFT', 'LF_PEAK_FFT', ...
            'LF_POWER_FFT', 'LF_TO_HF_FFT', 'TOTAL_POWER_FFT', 'VLF_NORM_FFT', 'VLF_POWER_FFT',  ...
            'SD1', 'SD2', 'alpha1', 'alpha2', 'SampEn', 'PIP', 'IALS', 'PSS', 'PAS', 'FK_ID'});
end
end
