
% Define Python executable file path (Python executables in Conda envs work
% just fine)
pathToPythonExec = '/home/preali/miniconda3/envs/ecg-omop/bin/python';

% Define the directory containing all Python scripts (must end with '/')
pyPath = '/mnt/hdd_data/preali/GitHubProjects/automatic-ecg-diagnosis/';

% Set the Python environment up if it hasn't been done yet.
% pyrun fails when loading Tensorflow, if pyenv is not called with the
% ExecutionMode set to OutOfProcess.
pe = pyenv;
if ~strcmp(pe.Executable,pathToPythonExec)
    pe = pyenv('Version',pathToPythonExec,'ExecutionMode','OutOfProcess');
end

% Import custom function in the persistent (=across multiple calls to the
% same function) environment generated by pyrun. As it is persistent, we
% need to import the function and the supporting modules only if a new
% Python environment has just been created, hence its status is not "Loaded".
needImport = ~strcmp(char(pe.Status),'Loaded');
if needImport
    origPath = cd(pyPath);
    pyrun('from predict_fun import predict_diagnosis');
end

% Call the function with the proper arguments from Matlab
% NB: Pandas Dataframes can be converted to Matlab tables starting with
%     Matlab R2024a (https://uk.mathworks.com/help/matlab/matlab_external/python-pandas-dataframes.html).
%     As for 2023a, which is the last version compatible with
%     Python 3.8 (the last version fully compatible with Ribeiro's ECG
%     automated diagnosis tool), we need to unpack the dataframe to its
%     components (namely, "y_score", "diagnosis", and "y_labels").
datapath = [pyPath,'test_data/ecg_tracings.hdf5'];
modelpath = [pyPath,'model/model.hdf5'];
outputpath = [pyPath,'dnn_output.csv'];
[df,y_score,diagnosis,y_labels] = pyrun(...
           "df,y_score,diagnosis,y_labels = predict_diagnosis(path_to_hdf5, path_to_model, output_csv_file=path_to_output)",...
           ["df","y_score","diagnosis","y_labels"],...
           path_to_hdf5=datapath,path_to_model=modelpath,path_to_output=outputpath);

% Convert Python outputs to valid Matlab variables formats
y_score = double(y_score);
y_labels = string(y_labels);
diagnosis = string(diagnosis);

% Go back to the initial path after the execution has teminated
if needImport, cd(origPath); end

% This works perfectly!